---
name: main

on:
  push:
  pull_request:
  workflow_dispatch:
  # schedule:
  #  - cron: "0 6 * * *"

defaults:
  run:
    shell: bash

jobs:
  containers:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        package: ["FSL", "Freesurfer"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: free disk space
        run: |
          set -euxo pipefail
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo docker image prune --all --force
          df -h
      - name: build image
        run: |
          set -euxo pipefail
          package="${{ matrix.package }}"
          cd "software/$package"
          img="ghcr.io/smi/${package,,}:$(grep _VERSION= Dockerfile | cut -d'"' -f2)"
          echo "$img"
          docker build . --tag "$img"
          # echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          # docker push "$img"
