---

name: main

on:
  push:
  pull_request:
  workflow_dispatch:
  # schedule:
  #  - cron: "0 6 * * *"

defaults:
  run:
    shell: bash

jobs:
  freesurfer:
    runs-on: ubuntu-22.04
    if: false # temp
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          set -euxo pipefail
          # Debug
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
          cd software/Freesurfer
          docker build .
  fsl:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          set -euxo pipefail
          # Debug
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
          cd software/FSL
          img="ghcr.io/smi/fsl:$(grep FSL_VERSION= Dockerfile | cut -d'"' -f2)"
          docker build . --tag "$img"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push "$img"
