---

name: main

on:
  push:
  pull_request:
  workflow_dispatch:
  # schedule:
  #  - cron: "0 6 * * *"

defaults:
  run:
    shell: bash

jobs:
  freesurfer:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          set -euxo pipefail
          # Debug
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
          cd software/Freesurfer
          podman build .
